GET http://localhost:8080

###
GET http://localhost:8080/info

###
GET http://localhost:8080/info/datainput?name=Ira&project=RecipeWebsite
###
GET http://localhost:8080/recipe/0
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "recipeName": "Test2",
  "cookingTime": 60,
  "ingredients": [
    {
      "name": "Test1",
      "count": 30,
      "measureUnit": "шт"
    }
  ],
  "stepsOfCooking": [
    "s1",
    "s2"
  ]
}
###
GET  http://localhost:8080/recipe/
###
PUT http://localhost:8080/recipe/7
Content-Type: application/json

{
  "recipeName": "Test12",
  "cookingTime": 50,
  "ingredients": [
    {
      "name": "Test2",
      "count": 30,
      "measureUnit": "шт"
    }
  ],
  "stepsOfCooking": [
    "s1",
    "s2"
  ]
}
###
DELETE  http://localhost:8080/recipe/1
###
http://localhost:8080/swagger-ui.html
###
GET  http://localhost:8080/ingredient
###
GET  http://localhost:8080/ingredient/2
###
DELETE  http://localhost:8080/ingredient/3
###
GET  http://localhost:8080/files/export/recipes
###
POST http://localhost:8080/files/import/recipes
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.json"
Content-Type: application/json

< ./recipes.json

###
POST http://localhost:8080/files/import/ingredients
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.json"
Content-Type: application/json

< ./ingredients.json
###
GET http://localhost:8080/files/export/recipes_txt
